"""Ordered fragment, methylation, bisulfite, and sequencing process."""

from .batch import (
    BaseState,
    CaptureStrand,
    ConversionMode,
    Fragment,
    FragmentSummary,
    Mate,
    MethylationAllele,
    MethylationContext,
    MethylationModelBatch,
    MethylationSite,
    MethylationSource,
    NO_VARIANT_INDEX,
    FastqFragment,
    FastqMate,
    EncodedFastqBatch,
    ColumnarFragmentBatch,
    ColumnarReadBatch,
    ProcessError,
    ProcessedFragment,
    ProcessedMate,
    READ_NAME_CONTRACT,
    ReadNameError,
    SiteReference,
    SiteState,
    UniformError,
    UniformQuality,
    Variant,
    VariantKind,
    format_fragment_identifier,
    fragment_identifier_coordinates,
)
from .config import ProcessConfig
from .methylation import BernoulliStateModel, MethylationStateModel
from .fragment import (
    decode_common_numpy_batch,
    decode_fragments,
    encode_fastq_batch,
    generate_columnar_reads,
    process_fragment_batch,
    supports_common_processing,
)

PROCESS_STAGE_ORDER = (
    "methylation",
    "fragment-orientation",
    "fragment-conversion",
    "mate-derivation",
    "quality",
    "sequencing-error",
    "format-ready",
)

__all__ = [
    "BaseState",
    "BernoulliStateModel",
    "CaptureStrand",
    "ConversionMode",
    "Fragment",
    "FragmentSummary",
    "Mate",
    "MethylationAllele",
    "MethylationContext",
    "MethylationModelBatch",
    "MethylationSite",
    "MethylationSource",
    "MethylationStateModel",
    "NO_VARIANT_INDEX",
    "FastqFragment",
    "FastqMate",
    "EncodedFastqBatch",
    "ColumnarFragmentBatch",
    "ColumnarReadBatch",
    "PROCESS_STAGE_ORDER",
    "ProcessConfig",
    "ProcessError",
    "ProcessedFragment",
    "ProcessedMate",
    "READ_NAME_CONTRACT",
    "ReadNameError",
    "SiteReference",
    "SiteState",
    "UniformError",
    "UniformQuality",
    "Variant",
    "VariantKind",
    "decode_common_numpy_batch",
    "decode_fragments",
    "encode_fastq_batch",
    "format_fragment_identifier",
    "fragment_identifier_coordinates",
    "generate_columnar_reads",
    "process_fragment_batch",
    "supports_common_processing",
]
