---
title: "GC bias"
author: "Wenbin Guo"
date: "2023-03-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(magrittr)
```


# load
```{r}
working_path = "~/iproject/BSReadSim/"
rds_path = paste0(working_path, "data/rds/")

length_res   = "100"
gc_bias_file = paste0(working_path, "/data/proc_data/ratio_depth_", length_res, "/ratio_depth.csv")
gc_bias_rds  = paste0(working_path, "/data/proc_data/ratio_depth_", length_res, "/ratio_depth.rds")

gc_bias_marked_rds = paste0(rds_path, "ratio_depth/marked_", length_res, ".rds")
gc_bias_cleaned_rds= paste0(rds_path, "ratio_depth/cleaned_", length_res, ".rds")
gc_bias_cleaned_summary_rds = paste0(rds_path, "ratio_depth/cleaned_summary_", length_res, ".rds")

gc_bias_marked_chr21_rds = paste0(rds_path, "ratio_depth/marked_chr21_", length_res, ".rds")
gc_bias_cleaned_chr21_rds= paste0(rds_path, "ratio_depth/cleaned_chr21_", length_res, ".rds")
gc_bias_cleaned_chr21_summary_rds = paste0(rds_path, "ratio_depth/cleaned_chr21_summary", length_res, ".rds")

bool_rerun = FALSE
bool_replot= TRUE
if(FALSE){
  gc_bias_df = read.table(gc_bias_file, sep = "\t", header = TRUE)
  gc_bias_df = gc_bias_df %>% 
    dplyr::mutate(bin=cut(ratio, breaks = seq(0,1,0.01), include.lowest = TRUE))

  if(length_res == "100"){
    merge_bin_lower = seq(0,0)
    merge_bin_upper = seq(0.9, 0.99, 0.01)
    gc_bias_df = gc_bias_df %>% 
      mutate(bin_group  = fct_collapse(bin, 
                                       "(0.9,1]"  = paste0("(", merge_bin_upper, ",", merge_bin_upper+0.01, "]")))
  }else if(length_res == "500"){
    merge_bin_lower = seq(0.01, 0.04, 0.01)
    merge_bin_upper = seq(0.85, 0.99, 0.01)
    gc_bias_df = gc_bias_df %>% 
      mutate(bin_group  = fct_collapse(bin, 
                                       "[0,0.05]" = c("[0,0.01]", paste0("(", merge_bin_lower, ",", merge_bin_lower+0.01, "]")),
                                       "(0.85,1]" = paste0("(", merge_bin_upper, ",", merge_bin_upper+0.01, "]")))
  }else{
    merge_bin_lower = seq(0.01, 0.24, 0.01)
    merge_bin_upper = seq(0.75, 0.99, 0.01)
    gc_bias_df = gc_bias_df %>% 
      mutate(bin_group  = fct_collapse(bin, 
                                       "[0,0.25]" = c("[0,0.01]", paste0("(", merge_bin_lower, ",", merge_bin_lower+0.01, "]")),
                                       "(0.75,1]" = paste0("(", merge_bin_upper, ",", merge_bin_upper+0.01, "]")))
  }
  saveRDS(gc_bias_df, gc_bias_rds)
}else{
  gc_bias_df = readRDS(gc_bias_rds)
}
```


# data processing
## bin distribution
```{r}
table(gc_bias_df$bin)
```

```{r}
table(gc_bias_df$bin_group)
```


##  remove outliers and summary
```{r}
mark_outlier = function(data, keep_chr = "chr21", in_col = "wgs_depth", out_col = "wgs_outlier"){
  data %>% filter(if(!!keep_chr != "all") chr_id == keep_chr else TRUE) %>% 
    rename(tmp_value=in_col) %>% 
    group_by(bin) %>%
    mutate(tmp_outlier = ifelse(tmp_value < quantile(tmp_value, 0.25) - 1.5 * IQR(tmp_value) | 
                                tmp_value > quantile(tmp_value, 0.75) + 1.5 * IQR(tmp_value), 1, 0)) %>%
    rename(!!in_col := tmp_value) %>% 
    rename(!!out_col:= tmp_outlier) %>% 
    ungroup() %>% as.data.frame()
}

#test normality for each bin using ks test (n>50)
#shapiro wilks sutiable for small sample size (n<=50), and cannot be used for > 5000
test_ks = function(df, df_summary, test = "pnorm"){
  bin_list = df_summary$bin_group
  df_test  = data.frame(bin_group = bin_list)
  df_test[paste0("wgs_", test)] = NA
  df_test[paste0("wgbs_",test)] = NA
  
  for(i in seq(length(bin_list))){
    bin_rec = bin_list[i]
    
    test_dat_wgs = df %>% dplyr::filter(bin_group == bin_rec) %>% pull(wgs_depth) %>% jitter()
    test_dat_wgbs= df %>% dplyr::filter(bin_group == bin_rec) %>% pull(wgbs_depth) %>% jitter()
    
    if(test == "pnorm"){
      test_ks_wgs  = ks.test(test_dat_wgs, "pnorm", mean = mean(test_dat_wgs),  sd = sd(test_dat_wgs))
      test_ks_wgbs = ks.test(test_dat_wgbs,"pnorm", mean = mean(test_dat_wgbs), sd = sd(test_dat_wgbs))
    }else if (test == "punif"){
      test_ks_wgs  = ks.test(test_dat_wgs, "punif", min(test_dat_wgs),  max(test_dat_wgs))
      test_ks_wgbs = ks.test(test_dat_wgbs,"punif", min(test_dat_wgbs), max(test_dat_wgbs))
    }else{
      print("haven't implement this test")
    }
    df_test[i, paste0(c("wgs_", "wgbs_"), test)] = c(test_ks_wgs$p.value, test_ks_wgbs$p.value)
  }
  return(df_test)
}

create_xlab = function(bin_group){
  split_vec = as.numeric(str_split(bin_group, pattern = "\\[|\\(|\\,|\\)|\\]")[[1]][2:3])
  if(abs(split_vec[1] - split_vec[2])>0.011){ # cannot 0.01, have rounding error issue
    return(ifelse(split_vec[1] == 0, paste0("<", split_vec[2]), paste0(">", split_vec[1])))
  }else{
    return(bin_group)
  }
}

## plotting needed
create_xtick= function(bin_group){
  split_vec = as.numeric(str_split(bin_group, pattern = "\\[|\\(|\\,|\\)|\\]")[[1]][2:3])
  if(abs(split_vec[1] - split_vec[2])>0.011){ # cannot 0.01, have rounding error issue
    return(ifelse(split_vec[1] == 0, split_vec[2], split_vec[1]))
  }else{
    return(split_vec[1])
  }
}

## scale a value
scale_val = function(x, x_vec, scale){
  x = ifelse(x < min(x_vec), min(x_vec), ifelse(x > max(x_vec), max(x_vec), x))
  return((x-min(x_vec))/(max(x_vec)-min(x_vec))*scale)
}
```


```{r}
if(bool_rerun){
  ## all 
  gc_bias_df_marked = gc_bias_df %>% 
    mark_outlier(keep_chr = "all",in_col = "wgs_depth", out_col = "wgs_outlier") %>% 
    mark_outlier(keep_chr = "all", in_col = "wgbs_depth", out_col = "wgbs_outlier")

  gc_bias_df_cleaned= gc_bias_df_marked %>% 
    dplyr::filter((wgs_outlier == 0) & (wgbs_outlier==0)) %>% 
    mutate(wgs_rdepth = wgs_depth /max(wgs_depth)) %>% 
    mutate(wgbs_rdepth= wgbs_depth/max(wgbs_depth))
  
  gc_bias_df_cleaned_summary = gc_bias_df_cleaned %>% 
    group_by(bin_group) %>% 
    summarise(num_obs   = length(wgs_depth),
              ratio_avg = mean(ratio),
              wgs_mean  = mean(wgs_depth),
              wgs_std   = sd(wgs_depth),
              wgs_max   = max(wgs_depth), 
              wgs_min   = min(wgs_depth), 
              wgs_median= median(wgs_depth)) %>% 
    left_join(gc_bias_df_cleaned %>% group_by(bin_group) %>% 
                summarise(wgbs_mean= mean(wgbs_depth),
                wgbs_std = sd(wgbs_depth),
                wgbs_max = max(wgbs_depth), 
                wgbs_min = min(wgbs_depth), 
                wgbs_median= median(wgbs_depth)), by = "bin_group")
  
  gc_bias_df_cleaned_summary = gc_bias_df_cleaned_summary %>% 
    left_join(test_ks(gc_bias_df_cleaned, gc_bias_df_cleaned_summary, test = "pnorm"),by = "bin_group") %>%  
    left_join(test_ks(gc_bias_df_cleaned, gc_bias_df_cleaned_summary, test = "punif"),by = "bin_group") %>% 
    mutate(xlab  = lapply(as.character(.$bin_group), FUN = create_xlab)) %>% 
    mutate(xlab  = factor(xlab, levels = xlab)) %>% 
    mutate(xtick = unlist(lapply(as.character(.$bin_group), FUN = create_xtick))) %>% 
    mutate(xlab2 = case_when(row_number()==1 ~ ifelse(xtick==0, as.character(xtick), as.character(xlab)), 
                             row_number()==n()~ifelse(xtick==1, as.character(xtick), as.character(xlab)),
                             TRUE ~ ifelse(xtick %in% seq(0, 1, 0.05), as.character(xtick), "")))
  
  ## chr21
  gc_bias_df_marked_chr21 = gc_bias_df %>% 
    mark_outlier(keep_chr = "chr21",in_col = "wgs_depth", out_col = "wgs_outlier") %>% 
    mark_outlier(keep_chr = "chr21", in_col = "wgbs_depth", out_col = "wgbs_outlier")
  
  gc_bias_df_cleaned_chr21= gc_bias_df_marked_chr21 %>% 
    dplyr::filter((wgs_outlier == 0) & (wgbs_outlier==0)) %>% 
    mutate(wgs_rdepth = wgs_depth/max(wgs_depth)) %>% 
    mutate(wgbs_rdepth= wgbs_depth/max(wgbs_depth))
  
  gc_bias_df_cleaned_chr21_summary = gc_bias_df_cleaned_chr21 %>% 
    group_by(bin_group) %>% 
    summarise(num_obs   = length(wgs_depth),
              ratio_avg = mean(ratio),
              wgs_mean  = mean(wgs_depth),
              wgs_std   = sd(wgs_depth),
              wgs_max   = max(wgs_depth), 
              wgs_min   = min(wgs_depth), 
              wgs_median= median(wgs_depth)) %>% 
    left_join(gc_bias_df_cleaned_chr21 %>% group_by(bin_group) %>% 
                summarise(wgbs_mean= mean(wgbs_depth),
                wgbs_std = sd(wgbs_depth),
                wgbs_max = max(wgbs_depth), 
                wgbs_min = min(wgbs_depth), 
                wgbs_median= median(wgbs_depth)), by = "bin_group")
  
  gc_bias_df_cleaned_chr21_summary = gc_bias_df_cleaned_chr21_summary %>% 
    left_join(test_ks(gc_bias_df_cleaned_chr21, gc_bias_df_cleaned_chr21_summary),by = "bin_group") %>% 
    left_join(test_ks(gc_bias_df_cleaned_chr21, gc_bias_df_cleaned_chr21_summary, test = "punif"),by = "bin_group") %>% 
    mutate(xlab  = lapply(as.character(.$bin_group), FUN = create_xlab)) %>% 
    mutate(xlab  = factor(xlab, levels = xlab)) %>% 
    mutate(xtick = unlist(lapply(as.character(.$bin_group), FUN = create_xtick))) %>% 
    mutate(xlab2 = case_when(row_number()==1 ~ ifelse(xtick==0, as.character(xtick), as.character(xlab)), 
                             row_number()==n()~ifelse(xtick==1, as.character(xtick), as.character(xlab)),
                             TRUE ~ ifelse(xtick %in% seq(0, 1, 0.05), as.character(xtick), "")))
  
  saveRDS(gc_bias_df_marked, file = gc_bias_marked_rds)
  saveRDS(gc_bias_df_cleaned, file = gc_bias_cleaned_rds)
  saveRDS(gc_bias_df_cleaned_summary, file = gc_bias_cleaned_summary_rds)
  
  saveRDS(gc_bias_df_marked_chr21, file = gc_bias_marked_chr21_rds)
  saveRDS(gc_bias_df_cleaned_chr21, file = gc_bias_cleaned_chr21_rds)
  saveRDS(gc_bias_df_cleaned_chr21_summary, file = gc_bias_cleaned_chr21_summary_rds)
}else{
  gc_bias_df_marked = readRDS(gc_bias_marked_rds)
  gc_bias_df_cleaned = readRDS(gc_bias_cleaned_rds)
  gc_bias_df_cleaned_summary = readRDS(gc_bias_cleaned_summary_rds)
  
  gc_bias_df_marked_chr21 = readRDS(gc_bias_marked_chr21_rds)
  gc_bias_df_cleaned_chr21 = readRDS(gc_bias_cleaned_chr21_rds)
  gc_bias_df_cleaned_chr21_summary = readRDS(gc_bias_cleaned_chr21_summary_rds)
}
```


# plot check
## all vs chr21
```{r}
summary_all_chr21_df = left_join(gc_bias_df_cleaned_summary[1:13], gc_bias_df_cleaned_chr21_summary[1:13], by = "bin_group")
summary_all_chr21_cor= cor(summary_all_chr21_df %>% dplyr::select(-c("bin_group")))
corrplot::corrplot(summary_all_chr21_cor[1:12, 1:12], title  = "all")
corrplot::corrplot(summary_all_chr21_cor[13:24, 13:24],title = "chr21")
corrplot::corrplot(summary_all_chr21_cor[1:12, 13:24], title = "all .vs. chr21")
```


## WGBS vs WGS relative depth 
```{r}
smoothScatter(gc_bias_df_cleaned$wgs_rdepth, gc_bias_df_cleaned$wgbs_rdepth, main = "all")
```

```{r}
smoothScatter(gc_bias_df_cleaned_chr21$wgs_rdepth, gc_bias_df_cleaned_chr21$wgbs_rdepth, main = "chr21")
```

## adaptive spline
### all
```{r}
plot_all_density_wgs  = ggplot(gc_bias_df_cleaned) +
  aes(x=ratio, y=wgs_depth) +
  labs(title = "WGS", subtitle="all", y = "Depth", x = "Ratio") +
  scale_y_continuous(name = "Depth",
                     sec.axis = sec_axis(~./max(gc_bias_df_cleaned$wgs_depth), name="Relative depth")) + 
  geom_hex(bins = 100) +
  scale_fill_continuous(type = "viridis") +
  geom_smooth(method='locfit', method.args = list(deg=1, alpha=0.3)) 

plot_all_density_wgbs = ggplot(gc_bias_df_cleaned) +
  aes(x=ratio, y=wgbs_depth) + 
  labs(title = "WGBS", subtitle="all", y = "Depth", x = "Ratio") +
  scale_y_continuous(name = "Depth",
                     sec.axis = sec_axis(~./max(gc_bias_df_cleaned$wgbs_depth), name="Relative depth")) + 
  geom_hex(bins = 100) +
  scale_fill_continuous(type = "viridis") +
  geom_smooth(method='locfit', method.args = list(deg=1, alpha=0.3))
```


### chr21
```{r}
library(locfit)

plot_chr21_density_wgbs_cs = ggplot(gc_bias_df_cleaned_chr21) +
  aes(x=ratio, y=wgbs_depth) +
  labs(title = "WGBS", subtitle="chr21  (gam cubic spline)", y = "Depth", x = "Ratio") +
  scale_y_continuous(name = "Depth",
                     sec.axis = sec_axis(~./max(gc_bias_df_cleaned_chr21$wgbs_depth), name="Relative depth")) + 
  geom_hex(bins = 100) +
  scale_fill_continuous(type = "viridis") +
  geom_smooth(method='gam', formula = y~s(x, bs="cs",m=2))

plot_chr21_density_wgbs_ad = ggplot(gc_bias_df_cleaned_chr21) +
  aes(x=ratio, y=wgbs_depth) +
  labs(title = "WGBS", subtitle="chr21  (gam adaptive smooth)", y = "Depth", x = "Ratio") +
  scale_y_continuous(name = "Depth",
                     sec.axis = sec_axis(~./max(gc_bias_df_cleaned_chr21$wgbs_depth), name="Relative depth")) + 
  geom_hex(bins = 100) +
  scale_fill_continuous(type = "viridis") +
  geom_smooth(method='gam', formula = y~s(x, bs="ad")) #slow

plot_chr21_density_wgbs_locfit = ggplot(gc_bias_df_cleaned_chr21) +
  aes(x=ratio, y=wgbs_depth) +
  labs(title = "WGBS", subtitle="chr21  (locfit)", y = "Depth", x = "Ratio") +
  scale_y_continuous(name = "Depth",
                     sec.axis = sec_axis(~./max(gc_bias_df_cleaned_chr21$wgbs_depth), name="Relative depth")) + 
  geom_hex(bins = 100) +
  scale_fill_continuous(type = "viridis") +
  geom_smooth(method='locfit', method.args = list(deg=1, alpha=0.3))

# geom_smooth(method = "loess") # too slow, 
## loess gives a better appearance, but is O(N2) in memory, so does not work for larger datasets.
## from https://ggplot2.tidyverse.org/reference/geom_smooth.html


plot_chr21_density_wgbs = ggplot(gc_bias_df_cleaned_chr21) +
  aes(x=ratio, y=wgbs_depth) +
  labs(title = "WGBS", subtitle="chr21", y = "Depth", x = "Ratio") +
  scale_y_continuous(name = "Depth",
                     sec.axis = sec_axis(~./max(gc_bias_df_cleaned_chr21$wgbs_depth), name="Relative depth")) + 
  geom_hex(bins = 100) +
  scale_fill_continuous(type = "viridis") +
  geom_smooth(method='locfit', method.args = list(deg=1, alpha=0.3))

plot_chr21_density_wgs = ggplot(gc_bias_df_cleaned_chr21) +
  aes(x=ratio, y=wgs_depth) +
  labs(title = "WGS", subtitle="chr21", y = "Depth", x = "Ratio") +
  scale_y_continuous(name = "Depth",
                     sec.axis = sec_axis(~./max(gc_bias_df_cleaned_chr21$wgs_depth), name="Relative depth")) + 
  geom_hex(bins = 100) +
  scale_fill_continuous(type = "viridis") +
  geom_smooth(method='locfit', method.args = list(deg=1, alpha=0.3))
```

```{r}
plot_chr21_density_wgbs_ad
plot_chr21_density_wgbs_cs
plot_chr21_density_wgbs_locfit
```


```{r}
plot_chr21_density_wgs
plot_chr21_density_wgbs
```


## boxplot
### code
```{r}
xtick_map = setNames(gc_bias_df_cleaned_chr21_summary$xlab2, gc_bias_df_cleaned_chr21_summary$bin_group)
theme_box = theme(axis.ticks.x = element_blank(),
                  axis.ticks=element_line(linewidth = 1),
                  axis.line = element_line(linetype = "solid"),
                  axis.text.x = element_text(vjust = -2),
                  axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
                  plot.margin = margin(b = 0.5, t = 0.5, l = 0.5, r = 0.5, unit = "cm"), # Adjust plot margin for tick visibility
                  plot.title = element_text(hjust = 0.5),
                  panel.grid.major = element_blank(),
                  panel.grid.minor = element_blank(),
                  panel.border = element_rect(colour = "black", fill=NA, linewidth=1),
                  panel.background = element_rect(fill = NA))

refine_plot = function(p){
  p + geom_boxplot(color = "blue", outlier.shape = NA) +
  scale_x_discrete(labels = gc_bias_df_cleaned_chr21_summary$xlab2)+
  scale_y_continuous(expand=c(0.01,0.01))+ 
  coord_cartesian(ylim = c(0, 90), clip="off") +
  # Add the custom x-axis ticks
  geom_segment(data  = ~ subset(.x, !duplicated(bin_group)),
               aes(x = bin_group, xend = bin_group, 
                   y = -1, yend = -1+ifelse(xtick_map[bin_group]=="", -0.5, -1)), 
               color = "black", linewidth = 0.5) + theme_box
}


## all 
plot_all_boxplot_wgs = refine_plot(
  ggplot(gc_bias_df_cleaned) +
    aes(x = bin_group, y = wgs_depth) +
    labs(title = "WGS", subtitle="all", y = "Depth", x = "Ratio")
)
  

plot_all_boxplot_wgbs = refine_plot(
  ggplot(gc_bias_df_cleaned) +
    aes(x = bin_group, y = wgbs_depth) +
    labs(title = "WGBS", subtitle="all", y = "Depth", x = "Ratio")
)

## chr21
plot_chr21_boxplot_wgs = refine_plot(
  ggplot(gc_bias_df_cleaned_chr21) +
    aes(x = bin_group, y = wgs_depth) +
    labs(title = "WGS", subtitle="chr21", y = "Depth", x = "Ratio")
)
  

plot_chr21_boxplot_wgbs = refine_plot(
  ggplot(gc_bias_df_cleaned_chr21) +
    aes(x = bin_group, y = wgbs_depth) +
    labs(title = "WGBS", subtitle="chr21", y = "Depth", x = "Ratio")
)
```

### show
```{r}
plot_all_boxplot_wgs
plot_all_boxplot_wgbs
plot_chr21_boxplot_wgs
plot_chr21_boxplot_wgbs
```


## save figure
```{r}
if(bool_replot){
  pdf(paste0(working_path, "data/figure/gcbias_res_", length_res, ".pdf"))
  corrplot::corrplot(summary_all_chr21_cor[1:12, 1:12], title  = "all")
  corrplot::corrplot(summary_all_chr21_cor[13:24, 13:24],title = "chr21")
  corrplot::corrplot(summary_all_chr21_cor[1:12, 13:24], title = "all .vs. chr21")
  
  smoothScatter(gc_bias_df_cleaned$wgs_rdepth, gc_bias_df_cleaned$wgbs_rdepth, main = "all")
  smoothScatter(gc_bias_df_cleaned_chr21$wgs_rdepth, gc_bias_df_cleaned_chr21$wgbs_rdepth, main = "chr21")
  
  plot(plot_chr21_density_wgbs_ad)
  plot(plot_chr21_density_wgbs_cs)
  plot(plot_chr21_density_wgbs_locfit)
  
  plot(plot_all_density_wgs)
  plot(plot_chr21_density_wgs)
  plot(plot_all_density_wgbs)
  plot(plot_chr21_density_wgbs)
  
  plot(plot_all_boxplot_wgs)
  plot(plot_chr21_boxplot_wgs)
  plot(plot_all_boxplot_wgbs)
  plot(plot_chr21_boxplot_wgbs)
  
  dev.off()
}
```
 

# overlay the density with box
```{r}
gc_bias_df_cleaned_chr21 = gc_bias_df_cleaned_chr21 %>% 
  mutate(x = scale_val(ratio, gc_bias_df_cleaned_chr21_summary$xtick, nrow(gc_bias_df_cleaned_chr21_summary)-1))


ggplot(gc_bias_df_cleaned_chr21, aes(x=x, y=wgbs_depth)) +
  scale_y_continuous(name = "Depth",
                     sec.axis = sec_axis(~./max(gc_bias_df_cleaned_chr21$wgbs_depth), name="relative depth"))+
  geom_smooth(aes(x=x, y=wgbs_depth), method='locfit', method.args = list(deg=1, alpha=0.3)) +
  stat_density2d(aes(fill = after_stat(density)), geom = "raster", contour = FALSE) +
  scale_fill_gradient(low = "white", high = "orange", na.value = NA) +
  geom_boxplot(aes(x = bin_group, y = wgbs_depth), color = "blue", outlier.shape = NA) +
  scale_x_discrete(labels = gc_bias_df_cleaned_chr21_summary$xlab) +
  geom_smooth(data = gc_bias_df_cleaned_chr21_summary, aes(x = x,  y = wgbs_median)) +
  theme(axis.line = element_line(linetype = "solid"),
    panel.grid.major = element_line(linetype = "blank"),
    panel.grid.minor = element_line(linetype = "blank"),
    plot.title = element_text(hjust = 0.5),
    panel.border = element_rect(colour = "black", fill=NA, linewidth=1),
    panel.background = element_rect(fill = NA)) +labs(title = "WGBS", subtitle="chr21", y = "Depth", x = "Ratio")
```



# fit loess or spline
## wgs

## wgbs
```{r}
loess_wgbs = loess(wgbs_median/max(wgbs_median) ~ ratio_avg, data=gc_bias_df_cleaned_summary, 
                   control=loess.control(surface="direct"))
loess_wgs  = loess(wgs_median/max(wgs_median) ~ ratio_avg, data=gc_bias_df_cleaned_summary,
                   control=loess.control(surface="direct"))

spline_wgbs = smooth.spline(gc_bias_df_cleaned_summary$ratio_avg, 
                            gc_bias_df_cleaned_summary$wgbs_median/max(gc_bias_df_cleaned_summary$wgbs_median), nknots = 20)
spline_wgs  = smooth.spline(gc_bias_df_cleaned_summary$ratio_avg, 
                            gc_bias_df_cleaned_summary$wgs_median/max(gc_bias_df_cleaned_summary$wgs_median), nknots = 20)

locfit_wgbs = locfit(wgbs_mean ~ ratio_avg, data = gc_bias_df_cleaned_chr21_summary, deg=1, alpha=0.3)
locfit_wgs  = locfit(wgs_mean ~ ratio_avg, data = gc_bias_df_cleaned_chr21_summary, deg=1, alpha=0.3)
```


```{r}

pred_locfit_wgbs= data.frame(
  ratio= gc_bias_df_cleaned_chr21_summary$xtick,
  pred = predict(locfit_wgbs, gc_bias_df_cleaned_chr21_summary$xtick)) %>% 
  mutate(x_plot = scale_x(ratio, ratio, nrow(gc_bias_df_cleaned_chr21_summary)),
         y_plot = scale_x(pred, range(gc_bias_df_cleaned_chr21_summary$wgbs_median), 
                          max(gc_bias_df_cleaned_chr21_summary$wgbs_median)))
```



```{r}
ggplot(gc_bias_df_cleaned_chr21, aes(x=ratio*91, y=wgbs_depth)) + # because boxplot plot by factor level
  # scale_y_continuous(name = "WGS Depth",sec.axis = sec_axis(~./max(gc_bias_df_cleaned_chr21$wgs_depth), name="WGS relative depth"))+
  stat_density2d(aes(fill = after_stat(density)), geom = "raster", contour = FALSE) +
  scale_fill_gradient(low = "white", high = "orange", na.value = NA) +
  geom_boxplot(aes(x = bin_group, y = wgbs_depth), color = "blue", outlier.shape = NA) +
  scale_x_discrete(labels = gc_bias_df_cleaned_chr21_summary$xlab)+
  geom_smooth(aes(x=ratio*100, y=wgbs_depth), method='gam') +
  #geom_smooth(data = gc_bias_df_cleaned_chr21_summary, aes(x = ratio_avg*100,  y = wgbs_median)) +
  theme(axis.line = element_line(linetype = "solid"),
    panel.grid.major = element_line(linetype = "blank"),
    panel.grid.minor = element_line(linetype = "blank"),
    plot.title = element_text(hjust = 0.5),
    panel.border = element_rect(colour = "black", fill=NA, linewidth=1),
    panel.background = element_rect(fill = NA)) +labs(title = "WGBS", subtitle="chr21", y = "Depth", x = "Ratio") 
```

