---
title: "Spline for RRBS"
author: "Wenbin Guo"
date: "2023-02-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# load
## package
```{r}
# Helper packages
library(dplyr)
library(ggplot2)
library(corrplot)

# Modeling packages
library(earth)
library(caret)
library(e1071)

# Model interpretability packages
library(vip)          # for variable importance
library(pdp)          # for variable relationships
library(ModelMetrics) # for access MSE, MAE
```


## path
```{r}
working_path = "~/iproject/BSReadSim/"
RRBS_path = paste0(working_path, "data/RRBS/")
plot_path = paste0(working_path, "docs/plot/")

frag_cut_file  = paste0(RRBS_path, "/frag_cut_df2.csv")

# linear regression
lm_ident_rds = paste0(RRBS_path, "/lm_ident.rds")
lm_logit_rds = paste0(RRBS_path, "/lm_logit.rds")

# beta regression
beta_reg_rds = paste0(RRBS_path, "/beta_reg.rds")

# spline
mars_ident_rds = paste0(RRBS_path, "/spline_ident.rds")
mars_logit_rds = paste0(RRBS_path, "/spline_logit.rds")
mars_cv_ident_rds = paste0(RRBS_path, "/spline_cv_ident.rds")
mars_cv_logit_rds = paste0(RRBS_path, "/spline_cv_logit.rds")

# GAM
gam3_rds  = paste0(RRBS_path, "/gam3.rds")
gam10_rds = paste0(RRBS_path, "/gam10.rds")
gam20_rds = paste0(RRBS_path, "/gam20.rds")

# sampling 
frag_cut_prob_bed = paste0(RRBS_path, "/frag_cut_prob.bed")

source(paste0(working_path, "/analysis/function.R"))
```


```{r}
scale_val = function(x, x_vec, scale){
  x = ifelse(x < min(x_vec), min(x_vec), ifelse(x > max(x_vec), max(x_vec), x))
  return((x-min(x_vec))/(max(x_vec)-min(x_vec))*scale)
}
```


## read-in
```{r}
frag_cut_df = read.table(frag_cut_file, sep = ",", header = TRUE) %>% 
  dplyr::mutate(logit_prob = log(relative_depth/(1-relative_depth)))

data_ident = frag_cut_df[c("length", "gc_ratio", "CCGG", "relative_depth")]
data_logit = frag_cut_df[c("length", "gc_ratio", "CCGG", "logit_prob")]

bool_rerun = FALSE
bool_rerun_plot = TRUE
```

```{r}
head(frag_cut_df)
```


# correlaiton
```{r}
scor_dat = data_ident
colnames(scor_dat) = c("Length", "GC ratio", "#CCGG", "Depth")
scor_mat = cor(scor_dat, method = "spearman")
scor_sig = cor.mtest(scor_dat, method = "spearman")
```

```{r, fig.height=4, fig.width=6}
par(mar = c(2, 2, 4, 2))
corrplot(scor_mat, p.mat = scor_sig$p, 
         method = 'circle', type = 'lower', insig='blank', sig.level = 0.05, tl.cex = 0.8,
         addCoef.col ='black', number.cex = 0.8, diag=FALSE, tl.srt = 0, tl.offset = 1, tl.col = "black")
```



# modeling
## liner regression
```{r}
if(bool_rerun){
  lm_ident = lm(relative_depth ~., data = data_ident)
  lm_logit = lm(logit_prob ~., data = data_logit)
  saveRDS(lm_ident, lm_ident_rds)
  saveRDS(lm_logit, lm_logit_rds)
}else{
  lm_ident = readRDS(lm_ident_rds)
  lm_logit = readRDS(lm_logit_rds)
}
```

```{r}
summary(lm_ident)
cat(paste0(paste(rep('-', 75), collapse = ""), "\n"))
summary(lm_logit)
```


## beta regression
```{r}
if(bool_rerun){
  library(betareg)
  beta_reg = betareg(relative_depth ~., data_ident)
  saveRDS(beta_reg, beta_reg_rds)
}else{
  beta_reg = readRDS(beta_reg_rds)
}
```

```{r}
# cannot summary, #Error: cannot allocate vector of size 590.3 Gb
cor(beta_reg$fitted.values, beta_reg$model$relative_depth)^2
```


## spline fit
on original relative_depth or logit transformed
```{r}
if(bool_rerun){
  mars_ident = earth(relative_depth ~ ., data = data_ident, degree=3) #glm=list(family=binomial)
  saveRDS(mars_ident, file = mars_ident_rds)
  
  mars_logit = earth(logit_prob ~ ., data = data_logit, degree=3)
  saveRDS(mars_logit, file = mars_logit_rds)
}else{
  mars_ident = readRDS(mars_ident_rds)
  mars_logit = readRDS(mars_logit_rds)
}
```


```{r}
summary(mars_ident)
cat(paste0(paste(rep('-', 75), collapse = ""), "\n"))
summary(mars_logit)
```


```{r}
plot(mars_ident, which = 1)
plot(mars_logit, which = 1)
```


## spline cross-validation
cross validation to select the best model
```{r}
hyper_grid <- expand.grid(
  degree = 1:5, 
  nprune = seq(2, 100, length.out = 10) %>% floor()
)

if(bool_rerun){
  library(doParallel)
  cl <- makePSOCKcluster(20)
  registerDoParallel(cl)
  
  set.seed(123)  # for reproducibility
  mars_cv_ident <- train(
    x = subset(data_ident, select = -relative_depth),
    y = data_ident$relative_depth,
    method = "earth",
    metric = "RMSE",
    trControl = trainControl(method = "cv", number = 10),
    tuneGrid = hyper_grid,
  )
  
  stopCluster(cl)
  
  saveRDS(mars_cv_ident, file = mars_cv_ident_rds)
  
  cl <- makePSOCKcluster(20)
  registerDoParallel(cl)
  
  set.seed(123)  # for reproducibility
  mars_cv_logit <- train(
    x = subset(data_logit, select = -logit_prob),
    y = data_logit$logit_prob,
    method = "earth",
    metric = "RMSE",
    trControl = trainControl(method = "cv", number = 10),
    tuneGrid = hyper_grid,
  )
  
  stopCluster(cl)
  
  saveRDS(mars_cv_logit, file = mars_cv_logit_rds)
}else{
  mars_cv_ident = readRDS(mars_cv_ident_rds)
  mars_cv_logit = readRDS(mars_cv_logit_rds)
}

head(hyper_grid)
```


```{r}
summary(mars_cv_ident)
cat(paste0(paste(rep('-', 75), collapse = ""), "\n"))
summary(mars_cv_logit)
```


## GAM
```{r}
library(mgcv)
library(splines)

if(bool_rerun){
  gam3  = mgcv::bam(logit_prob ~ ns(length, df=3) + ns(CCGG, df=1) + ns(gc_ratio, df=3), 
                    method = "fREML", data = data_logit)
  gam10 = mgcv::bam(relative_depth ~ ns(length, df=10) + ns(CCGG, df=1) + ns(gc_ratio, df=10), 
                    method = "fREML", data = data_ident, family = binomial(link = "probit"))
  gam20 = mgcv::bam(relative_depth ~ ns(length, df=20) + ns(CCGG, df=1) + ns(gc_ratio, df=20), 
                    method = "fREML", data = data_ident, family = betar)
  saveRDS(gam3, gam3_rds)
  saveRDS(gam10, gam10_rds)
  saveRDS(gam20, gam20_rds)
}else{
  gam3  = readRDS(gam3_rds)
  gam10 = readRDS(gam10_rds)
  gam20 = readRDS(gam20_rds)
}
```




# compare prediction results
```{r}
library(ggpointdensity)
library(viridis)

pred_df_ident = data.frame(real = mars_cv_ident$finalModel$y %>% as.vector(),
                           fitted = mars_cv_ident$finalModel$fitted.values %>% as.vector())
pred_df_logit = data.frame(real = mars_cv_logit$finalModel$y %>% as.vector(),
                           fitted = mars_cv_logit$finalModel$fitted.values %>% as.vector())

ggplot(pred_df_ident, mapping = aes(x = fitted, y = real)) +
  stat_density2d(aes(color = after_stat(density)), geom = "tile", contour = FALSE) +
  scale_color_viridis()

ggplot(pred_df_logit, mapping = aes(x = fitted, y = real)) +
  geom_pointdensity() # very slow
```



```{r, fig.width=5, fig.height=5}
par(pty = "s")
smoothScatter(x = lm_ident$model$relative_depth, 
              y = lm_ident$fitted.values, 
              main = "linear regression",
              xlab = "Actual depth", ylab = "Predicted depth", xlim = c(0,1), ylim = c(0,1))
# Add the regression line and R2
lm_model <- lm(lm_ident$fitted.values ~ lm_ident$model$relative_depth)
abline(lm_model, col = "red")
r_squared <- summary(lm_model)$r.squared
legend("topleft", legend = paste("R² =", round(r_squared, 3)), bty = "n")


smoothScatter(x = sigmoid(lm_logit$model$logit_prob), 
              y = sigmoid(lm_logit$fitted.values), 
              main = "linear regression (logit transformation)",
              xlab = "Actual depth", ylab = "Predicted depth", xlim = c(0,1), ylim = c(0,1))
# Add the regression line and R2
lm_model <- lm(sigmoid(lm_logit$fitted.values) ~ sigmoid(lm_logit$model$logit_prob))
abline(lm_model, col = "red")
r_squared <- summary(lm_model)$r.squared
legend("topleft", legend = paste("R² =", round(r_squared, 3)), bty = "n")


smoothScatter(x = beta_reg$model$relative_depth, 
              y = beta_reg$fitted.values, 
              main = "beta regression",
              xlab = "Actual depth", ylab = "Predicted depth", xlim = c(0,1), ylim = c(0,1))
# Add the regression line and R2
lm_model <- lm(beta_reg$fitted.values ~ beta_reg$model$relative_depth)
abline(lm_model, col = "red")
r_squared <- summary(lm_model)$r.squared
legend("topleft", legend = paste("R² =", round(r_squared, 3)), bty = "n")


smoothScatter(gam20$model$relative_depth,
              gam20$fitted.values,
              main = "GAM",
              xlab = "Actual depth", ylab = "Predicted depth", xlim = c(0,1), ylim = c(0,1))
# Add the regression line and R2
lm_model <- lm(gam20$fitted.values ~ gam20$model$relative_depth)
abline(lm_model, col = "red")
r_squared <- summary(lm_model)$r.squared
legend("topleft", legend = paste("R² =", round(r_squared, 3)), bty = "n")



smoothScatter(x = mars_cv_ident$trainingData$.outcome, 
              y = mars_cv_ident$finalModel$fitted.values, 
              main = "Multivariate spline", 
              xlab = "Actual depth", ylab = "Predicted depth", xlim = c(0,1), ylim = c(0,1))
# Add the regression line and R2
lm_model <- lm(mars_cv_ident$finalModel$fitted.values ~ mars_cv_ident$trainingData$.outcome)
abline(lm_model, col = "red") 
r_squared <- summary(lm_model)$r.squared
legend("topleft", legend = paste("R² =", round(r_squared, 3)), bty = "n")
```

# save figure
```{r}
if(bool_rerun_plot){
  rrbs_depth_cor_pred_figure = paste0(plot_path, "/rrbs_depth_cor_pred.pdf")
  save2pdf(file = rrbs_depth_cor_pred_figure, overwrite = TRUE,
           width = 5, height = 5, plot_code = quote({
            corrplot(scor_mat, p.mat = scor_sig$p, mar = c(1, 2, 2, 1),
                     method = 'circle', type = 'lower', insig='blank', sig.level = 0.05, tl.cex = 0.8,
                     addCoef.col ='black', number.cex = 0.8, diag=FALSE, tl.srt = 0, tl.offset = 1, tl.col = "black")

            par(pty = "s")
            smoothScatter(x = lm_ident$model$relative_depth, 
                          y = lm_ident$fitted.values, 
                          main = "linear regression",
                          xlab = "Actual depth", ylab = "Predicted depth", xlim = c(0,1), ylim = c(0,1))
            # Add the regression line and R2
            lm_model <- lm(lm_ident$fitted.values ~ lm_ident$model$relative_depth)
            abline(lm_model, col = "red")
            r_squared <- summary(lm_model)$r.squared
            legend("topleft", legend = paste("R² =", round(r_squared, 3)), bty = "n")
            
            
            smoothScatter(x = sigmoid(lm_logit$model$logit_prob), 
                          y = sigmoid(lm_logit$fitted.values), 
                          main = "linear regression (logit transformation)",
                          xlab = "Actual depth", ylab = "Predicted depth", xlim = c(0,1), ylim = c(0,1))
            # Add the regression line and R2
            lm_model <- lm(sigmoid(lm_logit$fitted.values) ~ sigmoid(lm_logit$model$logit_prob))
            abline(lm_model, col = "red")
            r_squared <- summary(lm_model)$r.squared
            legend("topleft", legend = paste("R² =", round(r_squared, 3)), bty = "n")
            
            
            smoothScatter(x = beta_reg$model$relative_depth, 
                          y = beta_reg$fitted.values, 
                          main = "beta regression",
                          xlab = "Actual depth", ylab = "Predicted depth", xlim = c(0,1), ylim = c(0,1))
            # Add the regression line and R2
            lm_model <- lm(beta_reg$fitted.values ~ beta_reg$model$relative_depth)
            abline(lm_model, col = "red")
            r_squared <- summary(lm_model)$r.squared
            legend("topleft", legend = paste("R² =", round(r_squared, 3)), bty = "n")
            
            
            smoothScatter(gam20$model$relative_depth,
                          gam20$fitted.values,
                          main = "GAM",
                          xlab = "Actual depth", ylab = "Predicted depth", xlim = c(0,1), ylim = c(0,1))
            # Add the regression line and R2
            lm_model <- lm(gam20$fitted.values ~ gam20$model$relative_depth)
            abline(lm_model, col = "red")
            r_squared <- summary(lm_model)$r.squared
            legend("topleft", legend = paste("R² =", round(r_squared, 3)), bty = "n")


            smoothScatter(x = mars_cv_ident$trainingData$.outcome, 
                          y = mars_cv_ident$finalModel$fitted.values, 
                          main = "Multivariate spline", 
                          xlab = "Actual depth", ylab = "Predicted depth", xlim = c(0,1), ylim = c(0,1))
            # Add the regression line and R2
            lm_model <- lm(mars_cv_ident$finalModel$fitted.values ~ mars_cv_ident$trainingData$.outcome)
            abline(lm_model, col = "red") 
            r_squared <- summary(lm_model)$r.squared
            legend("topleft", legend = paste("R² =", round(r_squared, 3)), bty = "n")
         }))
}
```

# save data
```{r}
if(bool_rerun){
  frag_cut_df$pred = as.vector(mars_cv_ident$finalModel$fitted.values)
  frag_cut_df$pred = ifelse(frag_cut_df$pred < 0, 0, frag_cut_df$pred)
  #frag_cut_df$prob = scale_val(frag_cut_df$pred, frag_cut_df$pred, 1)
  write.table(frag_cut_df %>% mutate(start0 = ref_l-1, end = ref_r, name = ".", strand = ".") %>% 
                dplyr::select(all_of(c("chr", "start0", "end", "name", "pred", "strand"))),
              file = frag_cut_prob_bed, sep = "\t", row.names = FALSE, quote = FALSE, col.names = FALSE)
}
```


